import { Notif, SampleData, PaginatedData, FilterData } from "./types";

export const sampleDatas: SampleData[] = [
  {
    data: [
      {
        id: 1,
        title: "Pos Duga Air (PDA)",
        normal: 1,
        siaga: 3,
        waspada: 2,
        total_data: 8,
        datasets: [
          {
            feature_id: 1,
            file_name: "Irigasi",
            store: "geovault:malang_irigasi",
            type: "Irigasi.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_irigasi&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-09-10",
            size: "10 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 2,
            file_name: "Jalan",
            store: "geovault:malang_jalan",
            type: "Jalan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_jalan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-09-11",
            size: "11 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 3,
            file_name: "Ladang",
            store: "geovault:malang_ladang",
            type: "Ladang.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_ladang&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-09-05",
            size: "11 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 4,
            file_name: "Pemanfaatan",
            store: "geovault:malang_pemanfaatan",
            type: "Pemanfaatan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemanfaatan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-06-29",
            size: "13 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 5,
            file_name: "Pemukiman",
            store: "geovault:malang_pemukiman",
            type: "Pemukiman.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemukiman&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-07-18",
            size: "15 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 6,
            file_name: "Perkebunan",
            store: "geovault:malang_perkebunan",
            type: "Perkebunan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_perkebunan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-07-18",
            size: "15 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 7,
            file_name: "Sawah",
            store: "geovault:malang_sawah",
            type: "Sawah.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sawah&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-07-20",
            size: "14 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 8,
            file_name: "Genangan",
            store: "geovault:malang_sawah",
            type: "Genangan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sawah&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-07-20",
            size: "14 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
        ],
      },
      {
        id: 2,
        title: "Pos Curah Hujan (PCH)",
        normal: 1,
        siaga: 1,
        waspada: 2,
        total_data: 5,
        datasets: [
          {
            feature_id: 9,
            file_name: "Pemanfaatan",
            store: "geovault:malang_pemanfaatan",
            type: "Pemanfaatan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemanfaatan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-06-29",
            size: "13 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 10,
            file_name: "Curah Hujan",
            store: "geovault:malang_curah_hujan01042024_05042024",
            type: "Curah Hujan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/wms?service=WMS&version=1.1.0&request=GetMap&layers=geovault%3Amalang_curah_hujan01042024_05042024&bbox=110.88803867171373%2C-8.785523478688916%2C116.27793037643086%2C-5.0395487439105136&width=768&height=533&srs=EPSG%3A4326&format=image%2Fgeotiff",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-04-01",
            size: "10 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 11,
            file_name: "Pemukiman",
            store: "geovault:malang_pemukiman",
            type: "Pemukiman.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemukiman&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-07-18",
            size: "15 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 12,
            file_name: "Perkebunan",
            store: "geovault:malang_perkebunan",
            type: "Perkebunan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_perkebunan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-07-18",
            size: "15 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 13,
            file_name: "Genangan",
            store: "geovault:malang_pemukiman",
            type: "Genangan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_perkebunan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-07-18",
            size: "15 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
        ],
      },
      {
        id: 3,
        title: "ARR",
        normal: 1,
        siaga: 2,
        waspada: 2,
        total_data: 11,
        datasets: [
          {
            feature_id: 14,
            file_name: "Ladang",
            store: "geovault:malang_ladang",
            type: "Ladang.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_ladang&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-09-05",
            size: "11 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 15,
            file_name: "Pemukiman",
            store: "geovault:malang_pemukiman",
            type: "Pemukiman.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemukiman&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-07-18",
            size: "15 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 16,
            file_name: "Toponim",
            store: "geovault:malang_toponim",
            type: "Toponim.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_toponim&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-09-01",
            size: "9 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 17,
            file_name: "Jalan",
            store: "geovault:malang_jalan",
            type: "Jalan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_jalan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-09-11",
            size: "11 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 18,
            file_name: "Perkebunan",
            store: "geovault:malang_perkebunan",
            type: "Perkebunan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_perkebunan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-07-18",
            size: "15 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 19,
            file_name: "Sawah",
            store: "geovault:malang_sawah",
            type: "Sawah.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sawah&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-07-20",
            size: "14 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 20,
            file_name: "Pemanfaatan",
            store: "geovault:malang_pemanfaatan",
            type: "Pemanfaatan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemanfaatan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-06-29",
            size: "13 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 21,
            file_name: "Sungai",
            store: "geovault:malang_sungai",
            type: "Sungai.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sungai&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-09-01",
            size: "9 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 22,
            file_name: "Genangan",
            store: "geovault:malang_sungai",
            type: "Genangan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sungai&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-09-01",
            size: "9 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 32,
            file_name: "Genangan",
            store: "geovault:malang_sungai",
            type: "Genangan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sungai&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-09-01",
            size: "9 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 33,
            file_name: "Penutupan Lahan",
            store: "geovault:malang_pemanfaatan",
            type: "Penutupan Lahan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sungai&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-09-11",
            size: "5 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
        ],
      },
      {
        id: 4,
        title: "AWLR",
        normal: 1,
        siaga: 1,
        waspada: 1,
        total_data: 9,
        datasets: [
          {
            feature_id: 22,
            file_name: "Curah Hujan",
            store: "geovault:malang_curah_hujan_01022024_05022024",
            type: "Curah Hujan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/wms?service=WMS&version=1.1.0&request=GetMap&layers=geovault%3Amalang_curah_hujan_01022024_05022024&bbox=110.88803867171373%2C-8.785523478688916%2C116.27793037643086%2C-5.0395487439105136&width=768&height=533&srs=EPSG%3A4326&styles=&format=image%2Fgeotiff",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-04-01",
            size: "10 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 23,
            file_name: "Ladang",
            store: "geovault:malang_ladang",
            type: "Ladang.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_ladang&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-09-05",
            size: "11 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 24,
            file_name: "Pemukiman",
            store: "geovault:malang_pemukiman",
            type: "Pemukiman.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemukiman&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-07-18",
            size: "15 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 25,
            file_name: "Toponim",
            store: "geovault:malang_toponim",
            type: "Toponim.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_toponim&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-09-01",
            size: "9 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 26,
            file_name: "Jalan",
            store: "geovault:malang_jalan",
            type: "Jalan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_jalan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-09-11",
            size: "11 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 27,
            file_name: "Sawah",
            store: "geovault:malang_sawah",
            type: "Sawah.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sawah&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-07-20",
            size: "14 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 28,
            file_name: "Pemanfaatan",
            store: "geovault:malang_pemanfaatan",
            type: "Pemanfaatan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemanfaatan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-06-29",
            size: "13 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 29,
            file_name: "Perkebunan",
            store: "geovault:malang_pemukiman",
            type: "Perkebunan.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_perkebunan&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Bondoyudo Bedadung",
            source: "Balai",
            date: "2024-07-18",
            size: "15 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 30,
            file_name: "Sungai",
            store: "geovault:malang_sungai",
            type: "Sungai.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sungai&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Madura Bawean",
            source: "Balai",
            date: "2024-09-01",
            size: "9 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
          {
            feature_id: 31,
            file_name: "Irigasi",
            store: "geovault:malang_irigasi",
            type: "Irigasi.zip",
            download:
              "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_irigasi&outputFormat=SHAPE-ZIP",
            bbws: "BBWS Brantas",
            ws: "WS Brantas",
            source: "Balai",
            date: "2024-09-11",
            size: "10 MB",
            status_qc: "Diterima",
            hasil_qc: "Update",
          },
        ],
      },
    ],
    all_data: [
      { id: 1, jenis_data: "Curah Hujan", total_data: 1 },
      { id: 2, jenis_data: "Irigasi", total_data: 2 },
      { id: 3, jenis_data: "Jalan", total_data: 3 },
      { id: 4, jenis_data: "Ladang", total_data: 3 },
      { id: 5, jenis_data: "Pemanfaatan", total_data: 4 },
      { id: 6, jenis_data: "Pemukiman", total_data: 4 },
      { id: 7, jenis_data: "Perkebunan", total_data: 4 },
      { id: 8, jenis_data: "Sawah", total_data: 3 },
      { id: 9, jenis_data: "Sungai", total_data: 2 },
      { id: 10, jenis_data: "Toponim", total_data: 2 },
      { id: 10, jenis_data: "Genangan", total_data: 5 },
      { id: 10, jenis_data: "Penutupan Lahan", total_data: 1 },
    ],
  },
];

export const filterDatas: FilterData[] = [
  {
    bulan: [
      {
        id: 1,
        value: "bulan_1",
        label: "Januari",
      },
      {
        id: 2,
        value: "bulan_2",
        label: "Februari",
      },
      {
        id: 3,
        value: "bulan_3",
        label: "Maret",
      },
      {
        id: 4,
        value: "bulan_4",
        label: "April",
      },
      {
        id: 5,
        value: "bulan_5",
        label: "Mei",
      },
      {
        id: 6,
        value: "bulan_6",
        label: "Juni",
      },
      {
        id: 7,
        value: "bulan_7",
        label: "Juli",
      },
      {
        id: 8,
        value: "bulan_8",
        label: "Agustus",
      },
      {
        id: 9,
        value: "bulan_9",
        label: "Septe mber",
      },
      {
        id: 10,
        value: "Bulan_10",
        label: "Oktober",
      },
      {
        id: 11,
        value: "bulan_11",
        label: "Nove mber",
      },
      {
        id: 12,
        value: "bulan_12",
        label: "Dese mber",
      },
    ],
    tahun: [
      {
        id: 1,
        value: "tahun_1",
        label: "2020",
      },
      {
        id: 2,
        value: "tahun_2",
        label: "2021",
      },
      {
        id: 3,
        value: "tahun_3",
        label: "2022",
      },
      {
        id: 4,
        value: "tahun_4",
        label: "2023",
      },
      {
        id: 5,
        value: "tahun_5",
        label: "2024",
      },
    ],
    wilayah_sungai: [
      {
        id: 1,
        value: "ws_1",
        label: "WS Bondoyudo Bedadung",
      },
      {
        id: 2,
        value: "ws_2",
        label: "WS Brantas",
      },
      {
        id: 3,
        value: "ws_3",
        label: "WS Cidanau Ciujung Cidurian",
      },
      {
        id: 4,
        value: "ws_4",
        label: "WS Ciliwung Cisadane",
      },
      {
        id: 5,
        value: "ws_5",
        label: "WS Cimanuk Cisanggarung",
      },
      {
        id: 6,
        value: "ws_6",
        label: "WS Ciwulan Cilaki",
      },
      {
        id: 7,
        value: "ws_7",
        label: "WS Citanduy",
      },
      {
        id: 8,
        value: "ws_8",
        label: "WS Citarum",
      },
      {
        id: 9,
        value: "ws_9",
        label: "WS Jratunseluna",
      },
      {
        id: 10,
        value: "ws_10",
        label: "WS Pemali Comal",
      },
      {
        id: 11,
        value: "ws_11",
        label: "WS Serayu Bogowonto",
      },
      {
        id: 12,
        value: "ws_12",
        label: "WS Progo Opak Serang",
      },
    ],
    bbws: [
      {
        id: 1,
        value: "bbws_1",
        label: "BBWS Brantas",
      },
      {
        id: 2,
        value: "bbws_2",
        label: "BBWS Cidanau Ciujung Cidurian",
      },
      {
        id: 3,
        value: "bbws_3",
        label: "BBWS Ciliwung Cisadane",
      },
      {
        id: 4,
        value: "bbws_4",
        label: "BBWS Cimanuk Cisanggarung",
      },
      {
        id: 5,
        value: "bbws_5",
        label: "BBWS Citanduy",
      },
      {
        id: 6,
        value: "bbws_6",
        label: "BBWS Citarum",
      },
      {
        id: 7,
        value: "bbws_7",
        label: "BBWS Pemali Juana",
      },
      {
        id: 8,
        value: "bbws_8",
        label: "BBWS Serayu Opak",
      },
    ],
    source: [
      {
        id: 1,
        value: "source_1",
        label: "Balai",
      },
      {
        id: 2,
        value: "source_2",
        label: "BMKG",
      },
      {
        id: 3,
        value: "source_3",
        label: "Pusat",
      },
    ],
    all_data: [
      {
        id: 1,
        value: "data_1",
        label: "curah hujan",
      },
      {
        id: 2,
        value: "data_2",
        label: "irigasi",
      },
      {
        id: 3,
        value: "data_3",
        label: "jalan",
      },
      {
        id: 4,
        value: "data_4",
        label: "ladang",
      },
      {
        id: 5,
        value: "data_5",
        label: "pemanfaatan",
      },
      {
        id: 6,
        value: "data_6",
        label: "pemukiman",
      },
      {
        id: 7,
        value: "data_7",
        label: "perkebunan",
      },
      {
        id: 8,
        value: "data_8",
        label: "sawah",
      },
      {
        id: 9,
        value: "data_9",
        label: "sungai",
      },
      {
        id: 10,
        value: "data_10",
        label: "toponim",
      },
      {
        id: 11,
        value: "data_11",
        label: "genangan",
      },
      {
        id: 12,
        value: "data_12",
        label: "Penutupan Lahan",
      },
    ],
    basemap: [
      {
        id: 1,
        jenis: "Satellite",
        layer_basemap:
          "https://api.maptiler.com/maps/satellite/{z}/{x}/{y}@2x.jpg?key=AW8IuG306IIk8kNdxEw6",
      },
      {
        id: 2,
        jenis: "Open Street Map",
        layer_basemap:
          "ihttps://api.maptiler.com/maps/streets-v2/{z}/{x}/{y}@2x.png?key=AW8IuG306IIk8kNdxEw6",
      },
    ],
  },
];

export const notifications: Notif[] = [
  {
    id: 1,
    file_name: "Curah Hujan",
    ws: "WS Bondoyudo Bedadung",
    date: "2024-09-01",
  },
  {
    id: 2,
    file_name: "Irigasi",
    ws: "WS Madura Bawean",
    date: "2024-09-04",
  },
  {
    id: 3,
    file_name: "Sungai",
    ws: "WS Brantas",
    date: "2024-09-03",
  },
  {
    id: 4,
    file_name: "Sawah",
    ws: "WS Bondoyudo Bedadung",
    date: "2024-09-02",
  },
  {
    id: 5,
    file_name: "Genangan",
    ws: "WS Brantas",
    date: "2024-09-05",
  },
];

export const paginationDatas: PaginatedData[] = [
  {
    currentPage: 1,
    totalPages: 3,
    pageSize: 11,
    totalItems: 33,
    data: [
      {
        feature_id: 1,
        file_name: "Irigasi",
        store: "geovault:malang_irigasi",
        type: "Irigasi.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_irigasi&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-09-10",
        size: "10 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 2,
        file_name: "Jalan",
        store: "geovault:malang_irigasi",
        type: "Jalan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_jalan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-09-11",
        size: "11 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 3,
        file_name: "Ladang",
        store: "geovault:malang_irigasi",
        type: "Ladang.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_ladang&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-09-05",
        size: "11 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 4,
        file_name: "Pemanfaatan",
        store: "geovault:malang_irigasi",
        type: "Pemanfaatan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemanfaatan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-06-29",
        size: "13 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 5,
        file_name: "Pemukiman",
        store: "geovault:malang_irigasi",
        type: "Pemukiman.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemukiman&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-07-18",
        size: "15 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 6,
        file_name: "Perkebunan",
        store: "geovault:malang_irigasi",
        type: "Perkebunan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_perkebunan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-07-18",
        size: "15 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 7,
        file_name: "Sawah",
        store: "geovault:malang_irigasi",
        type: "Sawah.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sawah&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-07-20",
        size: "14 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 8,
        file_name: "Genangan",
        store: "geovault:malang_irigasi",
        type: "Genangan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sawah&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-07-20",
        size: "14 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 9,
        file_name: "Pemanfaatan",
        store: "geovault:malang_irigasi",
        type: "Pemanfaatan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemanfaatan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-06-29",
        size: "13 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 10,
        file_name: "Curah Hujan",
        store: "geovault:malang_irigasi",
        type: "Curah Hujan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/wms?service=WMS&version=1.1.0&request=GetMap&layers=geovault%3Amalang_curah_hujan01042024_05042024&bbox=110.88803867171373%2C-8.785523478688916%2C116.27793037643086%2C-5.0395487439105136&width=768&height=533&srs=EPSG%3A4326&styles=&format=image%2Fgeotiff",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-04-01",
        size: "10 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 11,
        file_name: "Pemukiman",
        store: "geovault:malang_irigasi",
        type: "Pemukiman.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemukiman&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-07-18",
        size: "15 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
    ],
  },
  {
    currentPage: 2,
    totalPages: 3,
    pageSize: 11,
    totalItems: 33,
    data: [
      {
        feature_id: 12,
        file_name: "Perkebunan",
        store: "geovault:malang_irigasi",
        type: "Perkebunan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_perkebunan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-07-18",
        size: "15 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 13,
        file_name: "Genangan",
        store: "geovault:malang_irigasi",
        type: "Genangan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_perkebunan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-07-18",
        size: "15 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 14,
        file_name: "Ladang",
        store: "geovault:malang_irigasi",
        type: "Ladang.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_ladang&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-09-05",
        size: "11 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 15,
        file_name: "Pemukiman",
        store: "geovault:malang_irigasi",
        type: "Pemukiman.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemukiman&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-07-18",
        size: "15 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 16,
        file_name: "Toponim",
        store: "geovault:malang_irigasi",
        type: "Toponim.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_toponim&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-09-01",
        size: "9 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 17,
        file_name: "Jalan",
        store: "geovault:malang_irigasi",
        type: "Jalan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_jalan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-09-11",
        size: "11 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 18,
        file_name: "Perkebunan",
        store: "geovault:malang_irigasi",
        type: "Perkebunan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_perkebunan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-07-18",
        size: "15 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 19,
        file_name: "Pemanfaatan",
        store: "geovault:malang_irigasi",
        type: "Pemanfaatan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemanfaatan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-06-29",
        size: "13 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 20,
        file_name: "Sungai",
        store: "geovault:malang_irigasi",
        type: "Sungai.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sungai&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-09-01",
        size: "9 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 21,
        file_name: "Genangan",
        store: "geovault:malang_irigasi",
        type: "Genangan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sungai&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-09-01",
        size: "9 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 22,
        file_name: "Curah Hujan",
        store: "geovault:malang_irigasi",
        type: "Curah Hujan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/wms?service=WMS&version=1.1.0&request=GetMap&layers=geovault%3Amalang_curah_hujan_01022024_05022024&bbox=110.88803867171373%2C-8.785523478688916%2C116.27793037643086%2C-5.0395487439105136&width=768&height=533&srs=EPSG%3A4326&styles=&format=image%2Fgeotiff",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-04-01",
        size: "10 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
    ],
  },
  {
    currentPage: 3,
    totalPages: 4,
    pageSize: 9,
    totalItems: 33,
    data: [
      {
        feature_id: 23,
        file_name: "Ladang",
        store: "geovault:malang_irigasi",
        type: "Ladang.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_ladang&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-09-05",
        size: "11 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 24,
        file_name: "Pemukiman",
        store: "geovault:malang_irigasi",
        type: "Pemukiman.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_pemukiman&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-07-18",
        size: "15 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 25,
        file_name: "Toponim",
        store: "geovault:malang_irigasi",
        type: "Toponim.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_toponim&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-09-01",
        size: "9 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 26,
        file_name: "Jalan",
        store: "geovault:malang_irigasi",
        type: "Jalan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_jalan&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-09-11",
        size: "11 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 27,
        file_name: "Sawah",
        store: "geovault:malang_irigasi",
        type: "Sawah.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sawah&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Bondoyudo Bedadung",
        source: "Balai",
        date: "2024-07-20",
        size: "14 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 28,
        file_name: "Sungai",
        store: "geovault:malang_irigasi",
        type: "Sungai.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sungai&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Madura Bawean",
        source: "Balai",
        date: "2024-09-01",
        size: "9 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 29,
        file_name: "Irigasi",
        store: "geovault:malang_irigasi",
        type: "Irigasi.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_irigasi&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-09-10",
        size: "10 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 30,
        file_name: "Genangan",
        store: "geovault:malang_irigasi",
        type: "Genangan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_irigasi&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-09-10",
        size: "10 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 31,
        file_name: "Penutupan Lahan",
        store: "geovault:malang_irigasi",
        type: "Penutupan Lahan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_irigasi&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-09-10",
        size: "10 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 32,
        file_name: "Genangan",
        store: "geovault:malang_irigasi",
        type: "Genangan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_irigasi&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-09-10",
        size: "10 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
      {
        feature_id: 33,
        file_name: "Penutupan Lahan",
        store: "geovault:malang_irigasi",
        type: "Penutupan Lahan.zip",
        download:
          "http://localhost:8080/geoserver/geovault/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geovault%3Amalang_sungai&outputFormat=SHAPE-ZIP",
        bbws: "BBWS Brantas",
        ws: "WS Brantas",
        source: "Balai",
        date: "2024-09-11",
        size: "5 MB",
        status_qc: "Diterima",
        hasil_qc: "Update",
      },
    ],
  },
];
